### ISSUE TITLE
Ability to retry on ResponseError

### ISSUE THREAD

**Issue by Gee-Bee** [fieldhand/fieldhand#17]
During harvesting the service randomly returned 500 server error
```bash
Fieldhand::ResponseError (Invalid response: 500 Internal Server Error)
```
Due to this I had to start harvesting from the beginning, because there is no mechanism to retry. It was really annoying on large dataset, so I end up monkey patching `Fieldhand::Paginator#request` method.
```ruby
module Fieldhand
  class Paginator

    private

    alias_method :original_request_method, :request

    def request(query = {})
      send(:original_request_method, query).tap do |response|
        logger.debug('Fieldhand') { response.body }
      end
    rescue => e
      retries = retries.to_i + 1
      if retries < 30
        delay = retries * retries
        logger.warn('Fieldhand') { "Error fetching response: [#{e.class}] #{e}\nRetrying in #{delay} seconds" }
        sleep delay
        retry
      else
        raise e
      end
    end
  end
end
```
It would be really helpful to have such a mechanism in a gem.

**Comment by mudge** [comment]
Hi @Gee-Bee,

We've now added two new options you can pass to `Fieldhand::Repository` in [the new 0.12.0 release of Fieldhand](https://rubygems.org/gems/fieldhand/versions/0.12.0):

* `retries`: the maximum number of times an unsuccessful HTTP request will be retried (defaults to 0 for backward compatibility);
* `interval`: the number of seconds to wait between retries (defaults to 10).

```ruby
repository = Fieldhand::Repository.new('http://www.example.com/oai', :retries => 5, :interval => 30)
```

Thanks to @MarcoBgn for contributing this and please let me know if this resolves your issue!
